name: fluent-bit # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap

version: '3.2.0' # just for humans, typically '1.2+git' or '1.3.2'

summary: 'Fluent Bit: community-driven, Apache 2.0-licensed search and analytics suite.'
description: |
  Fluent Bit is a fast Log Processor and Forwarder for Linux, Windows, Embedded Linux, MacOS and BSD family operating systems.
  It's part of the Graduated Fluentd Ecosystem and a CNCF sub-project and is Apache 2.0-licensed.
  Fluent Bit allows to collect log events or metrics from different sources, process them and deliver them to different 
  backends such as Fluentd, Elasticsearch, Splunk, DataDog, Kafka, New Relic, Azure services, AWS services, Google services, 
  NATS, InfluxDB or any custom HTTP end-point.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

architectures:
  - amd64

system-usernames:
  snap_daemon: shared

hooks:
  install:
    plugs:
      - network
      - network-bind

environment:
  SNAP_CURRENT: /snap/opensearch/current
  SNAP_DATA_CURRENT: /var/snap/opensearch/current

apps:
  daemon:
    daemon: simple
    install-mode: disable
    command: bin/fluent-bit -i cpu -o stdout -f 1
    restart-condition: always
    restart-delay: 1s
    plugs:
      - network
      - network-bind
      - hardware-observe
      - log-observe
      - mount-observe
      - process-control
      - system-observe

parts:
  libressl:
    plugin: autotools
    source: https://github.com/libressl/portable/releases/download/v4.0.0/libressl-4.0.0.tar.gz
    build-packages:
      - build-essential
      - autotools-dev
      - automake
      - libtool
    override-build: |
      set -eux
      ls -la
      ./configure --prefix="${SNAPCRAFT_PART_INSTALL}"
      make -j$(nproc)
      make install
    stage:
      - lib/
      - include/

  nghttp3:
    plugin: autotools
    source: https://github.com/ngtcp2/nghttp3/releases/download/v1.6.0/nghttp3-1.6.0.tar.gz
    build-packages:
      - build-essential
      - autoconf
      - libtool
      - pkg-config
    override-build: |
      autoreconf -i
      ./configure --prefix="${SNAPCRAFT_PART_INSTALL}" --enable-lib-only
      make -j$(nproc)
      make install
    stage:
      - lib/
      - include/

  ngtcp2:
    plugin: autotools
    source: https://github.com/ngtcp2/ngtcp2/releases/download/v1.8.1/ngtcp2-1.8.1.tar.gz
    after:
      - libressl
      - nghttp3
    build-packages:
      - build-essential
      - autoconf
      - libtool
      - pkg-config
    override-build: |
      autoreconf -i
      PKG_CONFIG_PATH="${SNAPCRAFT_STAGE}/lib/pkgconfig" ./configure --prefix="${SNAPCRAFT_PART_INSTALL}" --enable-lib-only
      make -j$(nproc)
      make install
    stage:
      - lib/
      - include/

  build:
    plugin: dump
    source: https://github.com/fluent/fluent-bit.git
    source-type: git
    source-commit: 50512ed56aad32f07d98a723cb217f0251bb52e8
    after:
      - libressl
      - nghttp3
      - ngtcp2
    build-packages:
      - bison
      - cmake
      - flex
      - make
      - pkg-config
      - util-linux
      - valgrind
      - libyaml-dev
      - libedit-dev
      - libev-dev
      - libc-ares-dev
      - libsystemd-dev
      - libjansson-dev
      - libevent-dev
      - libsasl2-dev
      - libcunit1-dev
      - libxml2-dev
      - libjemalloc-dev
      - libpq-dev
      - libssl-dev
    stage-packages:
      - libyaml-0-2
      - libedit2
      - libev4
      - libc-ares2
      - libsystemd0
      - libjansson4
      - libevent-2.1-7
      - libsasl2-2
      - libcunit1
      - libxml2
      - libjemalloc2
      - libpq5
      - libssl3
    override-build: |
      set -eux
      echo -e "\n\n\n-------------------------------------\n\n\n"
      cd build
      echo -e "\n\n\n-------------------------------------\n\n\n"
      cmake -DCMAKE_INSTALL_PREFIX="${SNAPCRAFT_PART_INSTALL}" \
        -DCMAKE_PREFIX_PATH="${SNAPCRAFT_STAGE}" \
        -DCMAKE_LIBRARY_PATH="${SNAPCRAFT_STAGE}/lib" \
        -DCMAKE_INCLUDE_PATH="${SNAPCRAFT_STAGE}/include" \
        ..
      echo -e "\n\n\n-------------------------------------\n\n\n"
      make -j$(nproc)
      echo -e "\n\n\n-------------------------------------\n\n\n"
      make install
      echo -e "\n\n\n-------------------------------------\n\n\n"
      ldd bin/fluent-bit
      echo -e "\n\n\n-------------------------------------\n\n\n"
      ls -la $SNAPCRAFT_STAGE/lib
      echo -e "\n\n\n-------------------------------------\n\n\n"
      ls -la $SNAPCRAFT_STAGE/include
      echo -e "\n\n\n-------------------------------------\n\n\n"
