name: opensearch # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap

version: '2.14.0' # just for humans, typically '1.2+git' or '1.3.2'

summary: 'OpenSearch: community-driven, Apache 2.0-licensed search and analytics suite.'
description: |
  Fluent Bit is a fast Log Processor and Forwarder for Linux, Windows, Embedded Linux, MacOS and BSD family operating systems.
  It's part of the Graduated Fluentd Ecosystem and a CNCF sub-project and is Apache 2.0-licensed.
  Fluent Bit allows to collect log events or metrics from different sources, process them and deliver them to different 
  backends such as Fluentd, Elasticsearch, Splunk, DataDog, Kafka, New Relic, Azure services, AWS services, Google services, 
  NATS, InfluxDB or any custom HTTP end-point.

grade: stable # must be 'stable' to release into candidate/stable channels

confinement: strict # use 'strict' once you have the right plugs and slots


architectures:
  - amd64
  - arm64


system-usernames:
  snap_daemon: shared


hooks:
  install:
    plugs:
      - network
      - network-bind


environment:
  SNAP_CURRENT: /snap/opensearch/current
  SNAP_DATA_CURRENT: /var/snap/opensearch/current


apps:
  daemon:
    daemon: simple
    install-mode: disable
    command: opt/fluent-bit/start.sh
    restart-condition: always
    restart-delay: 1s
    plugs:
      - network
      - network-bind
      - hardware-observe
      - log-observe
      - mount-observe
      - process-control
      - system-observe


parts:
  build:
    plugin: dump
    source: https://github.com/fluent/fluent-bit.git
    source-type: git
    source-commit: e28f4479958918faa41615158a744d29b0f893fa
    build-packages:
      - bison
      - cmake
      - flex
      - make
      - openssl
      - util-linux
      - valgrind
    override-build: |
      ls -la 
      cd build
      cmake ..
      make
      bin/fluent-bit -i cpu -o stdout -f 1

